# Debug configuration for Neural integration
# Add this to your configuration.yaml to enable debug logging

# Enable debug logging for the integration
logger:
  custom_components.neural: debug
  custom_components.neural.coordinator: debug
  custom_components.neural.core.api.ai_client: debug
  custom_components.neural.core.api.ha_client: debug
  custom_components.neural.core.api.ha_auth_client: debug

# Example service call to test the integration
# You can call this service from Developer Tools > Services
# service: neural.change_language
# data:
#   language: "en"

# Example automation to test alarm names
# automation:
#   - alias: "Test Alarm Names"
#     trigger:
#       platform: time
#       at: "12:00:00"
#     action:
#       - service: neural.change_language
#         data:
#           language: "es"
#       - delay:
#           seconds: 5
#       - service: neural.change_language
#         data:
#           language: "en" 