# Services for Neural AI integration

# Send a message to the AI
send_message:
  name: "Send Message to AI"
  description: "Send a message to the Neural AI and get a response"
  target:
    entity:
      integration: neural
      domain: sensor
  fields:
    message:
      name: "Message"
      description: "The message to send to the AI"
      required: true
      selector:
        text:

# Get AI status
get_status:
  name: "Get AI Status"
  description: "Get the current status of the Neural AI service"
  target:
    entity:
      integration: neural
      domain: sensor

# Update configuration
update_config:
  name: "Update Configuration"
  description: "Update Neural AI configuration"
  target:
    entity:
      integration: neural
      domain: sensor
  fields:
    config:
      name: "Configuration"
      description: "Configuration parameters to update"
      required: true
      selector:
        object:
