# Services for Neural AI integration

# Send a message to AI
send_message:
  name: "Send Message to AI"
  description: "Send a message to the AI and get a response"
  target:
    entity:
      integration: neural
      domain: sensor
  fields:
    message:
      name: "Message"
      description: "The message to send to the AI"
      required: true
      selector:
        text:
    model:
      name: "AI Model"
      description: "The AI model to use (optional)"
      required: false
      selector:
        text:

# Get AI status
get_status:
  name: "Get AI Status"
  description: "Get the current status of the AI service"
  target:
    entity:
      integration: neural
      domain: sensor

# List available AI models
list_models:
  name: "List AI Models"
  description: "List all available AI models"
  target:
    entity:
      integration: neural
      domain: sensor