# Services for My Verisure integration

# Arm the alarm in away mode
arm_away:
  name: "Arm Alarm Away"
  description: "Arm the alarm in away mode (total)"
  target:
    entity:
      integration: my_verisure
      domain: alarm_control_panel
  fields:
    installation_id:
      name: "Installation ID"
      description: "The installation ID to arm"
      required: true
      selector:
        text:

# Arm the alarm in home mode
arm_home:
  name: "Arm Alarm Home"
  description: "Arm the alarm in home mode (perimeter)"
  target:
    entity:
      integration: my_verisure
      domain: alarm_control_panel
  fields:
    installation_id:
      name: "Installation ID"
      description: "The installation ID to arm"
      required: true
      selector:
        text:

# Arm the alarm in night mode
arm_night:
  name: "Arm Alarm Night"
  description: "Arm the alarm in night mode"
  target:
    entity:
      integration: my_verisure
      domain: alarm_control_panel
  fields:
    installation_id:
      name: "Installation ID"
      description: "The installation ID to arm"
      required: true
      selector:
        text:

# Disarm the alarm
disarm:
  name: "Disarm Alarm"
  description: "Disarm the alarm"
  target:
    entity:
      integration: my_verisure
      domain: alarm_control_panel
  fields:
    installation_id:
      name: "Installation ID"
      description: "The installation ID to disarm"
      required: true
      selector:
        text:

# Get alarm status
get_status:
  name: "Get Alarm Status"
  description: "Refresh the alarm status"
  target:
    entity:
      integration: my_verisure
      domain: alarm_control_panel
  fields:
    installation_id:
      name: "Installation ID"
      description: "The installation ID to get status for"
      required: true
      selector:
        text:

 